### ISSUE TITLE
Image Not Displaying on Get Started Page

### ISSUE THREAD

**Issue by mcjill** [apitoolkit/apitoolkit-landing#134]
The image specified for the Get Started page is not displaying on the website. Interestingly, it appears correctly in the markdown on GitHub.
![Screenshot 2023-12-13 at 15-58-49 apitoolkit-landing_content_docs_getstarted md at master · apitoolkit_apitoolkit-landing](https://github.com/apitoolkit/apitoolkit-landing/assets/66503402/5361fa17-5a39-4700-bc2d-b02463e4d121)
![Screenshot 2023-12-13 at 15-57-08 Get Started - APIToolkit](https://github.com/apitoolkit/apitoolkit-landing/assets/66503402/faa2b4e6-5af7-4846-9124-e06b73640638)

**Comment by tonyalaribe** [comment]
Thanks for pointing it out. Seems like a path issue.
